
package org.example.weatherclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Service to get weather information for given coordinates
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CoordinatesToWeatherService", targetNamespace = "http://www.example.org/CoordinatesToWeatherService", wsdlLocation = "http://localhost:8081/wsdl/CoordinatesToWeatherService.wsdl")
public class CoordinatesToWeatherService
    extends Service
{

    private final static URL COORDINATESTOWEATHERSERVICE_WSDL_LOCATION;
    private final static WebServiceException COORDINATESTOWEATHERSERVICE_EXCEPTION;
    private final static QName COORDINATESTOWEATHERSERVICE_QNAME = new QName("http://www.example.org/CoordinatesToWeatherService", "CoordinatesToWeatherService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/wsdl/CoordinatesToWeatherService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COORDINATESTOWEATHERSERVICE_WSDL_LOCATION = url;
        COORDINATESTOWEATHERSERVICE_EXCEPTION = e;
    }

    public CoordinatesToWeatherService() {
        super(__getWsdlLocation(), COORDINATESTOWEATHERSERVICE_QNAME);
    }

    public CoordinatesToWeatherService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COORDINATESTOWEATHERSERVICE_QNAME, features);
    }

    public CoordinatesToWeatherService(URL wsdlLocation) {
        super(wsdlLocation, COORDINATESTOWEATHERSERVICE_QNAME);
    }

    public CoordinatesToWeatherService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COORDINATESTOWEATHERSERVICE_QNAME, features);
    }

    public CoordinatesToWeatherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoordinatesToWeatherService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CoordinatesToWeatherPortType
     */
    @WebEndpoint(name = "CoordinatesToWeatherPort")
    public CoordinatesToWeatherPortType getCoordinatesToWeatherPort() {
        return super.getPort(new QName("http://www.example.org/CoordinatesToWeatherService", "CoordinatesToWeatherPort"), CoordinatesToWeatherPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoordinatesToWeatherPortType
     */
    @WebEndpoint(name = "CoordinatesToWeatherPort")
    public CoordinatesToWeatherPortType getCoordinatesToWeatherPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/CoordinatesToWeatherService", "CoordinatesToWeatherPort"), CoordinatesToWeatherPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COORDINATESTOWEATHERSERVICE_EXCEPTION!= null) {
            throw COORDINATESTOWEATHERSERVICE_EXCEPTION;
        }
        return COORDINATESTOWEATHERSERVICE_WSDL_LOCATION;
    }

}
