
package org.example.weatherclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CoordinatesToWeatherPortType", targetNamespace = "http://www.example.org/CoordinatesToWeatherService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoordinatesToWeatherPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.weatherclient.GetWeatherResponse
     */
    @WebMethod(operationName = "GetWeather", action = "http://www.example.org/CoordinatesToWeatherService/GetWeather")
    @WebResult(name = "GetWeatherResponse", targetNamespace = "http://www.example.org/CoordinatesToWeatherService", partName = "parameters")
    public GetWeatherResponse getWeather(
        @WebParam(name = "GetWeatherRequest", targetNamespace = "http://www.example.org/CoordinatesToWeatherService", partName = "parameters")
        GetWeatherRequest parameters);

}
