<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:tns="http://localhost/CoordinatesToWeatherService"
             targetNamespace="http://localhost/CoordinatesToWeatherService">

    <types>
        <xsd:schema>
            <xsd:import namespace="http://localhost/CoordinatesToWeatherService"
                        schemaLocation="CoordinatesToWeatherService.xsd"/>
        </xsd:schema>
    </types>

    <message name="GetWeatherRequest">
        <part name="parameters" element="tns:GetWeatherRequest"/>
    </message>
    <message name="GetWeatherResponse">
        <part name="parameters" element="tns:GetWeatherResponse"/>
    </message>

    <portType name="CoordinatesToWeatherPortType">
        <operation name="GetWeather">
            <input message="tns:GetWeatherRequest"/>
            <output message="tns:GetWeatherResponse"/>
        </operation>
    </portType>

    <binding name="CoordinatesToWeatherBinding" type="tns:CoordinatesToWeatherPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetWeather">
            <soap:operation soapAction="http://localhost/CoordinatesToWeatherService/GetWeather"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="CoordinatesToWeatherService">
        <port name="CoordinatesToWeatherPort" binding="tns:CoordinatesToWeatherBinding">
            <soap:address location="http://localhost:8081/ws"/>
        </port>
    </service>
</definitions>
