
package org.example.cityclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Service to get coordinates for a given city name
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CityToCoordinatesService", targetNamespace = "http://www.example.org/CityToCoordinatesService", wsdlLocation = "http://localhost:8080/wsdl/CityToCoordinatesService.wsdl")
public class CityToCoordinatesService
    extends Service
{

    private final static URL CITYTOCOORDINATESSERVICE_WSDL_LOCATION;
    private final static WebServiceException CITYTOCOORDINATESSERVICE_EXCEPTION;
    private final static QName CITYTOCOORDINATESSERVICE_QNAME = new QName("http://www.example.org/CityToCoordinatesService", "CityToCoordinatesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wsdl/CityToCoordinatesService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CITYTOCOORDINATESSERVICE_WSDL_LOCATION = url;
        CITYTOCOORDINATESSERVICE_EXCEPTION = e;
    }

    public CityToCoordinatesService() {
        super(__getWsdlLocation(), CITYTOCOORDINATESSERVICE_QNAME);
    }

    public CityToCoordinatesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CITYTOCOORDINATESSERVICE_QNAME, features);
    }

    public CityToCoordinatesService(URL wsdlLocation) {
        super(wsdlLocation, CITYTOCOORDINATESSERVICE_QNAME);
    }

    public CityToCoordinatesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CITYTOCOORDINATESSERVICE_QNAME, features);
    }

    public CityToCoordinatesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CityToCoordinatesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CityToCoordinatesPortType
     */
    @WebEndpoint(name = "CityToCoordinatesPort")
    public CityToCoordinatesPortType getCityToCoordinatesPort() {
        return super.getPort(new QName("http://www.example.org/CityToCoordinatesService", "CityToCoordinatesPort"), CityToCoordinatesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CityToCoordinatesPortType
     */
    @WebEndpoint(name = "CityToCoordinatesPort")
    public CityToCoordinatesPortType getCityToCoordinatesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/CityToCoordinatesService", "CityToCoordinatesPort"), CityToCoordinatesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CITYTOCOORDINATESSERVICE_EXCEPTION!= null) {
            throw CITYTOCOORDINATESSERVICE_EXCEPTION;
        }
        return CITYTOCOORDINATESSERVICE_WSDL_LOCATION;
    }

}
