
package org.example.cityclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CityToCoordinatesPortType", targetNamespace = "http://www.example.org/CityToCoordinatesService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CityToCoordinatesPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.cityclient.GetCoordinatesResponse
     */
    @WebMethod(operationName = "GetCoordinates", action = "http://www.example.org/CityToCoordinatesService/GetCoordinates")
    @WebResult(name = "GetCoordinatesResponse", targetNamespace = "http://www.example.org/CityToCoordinatesService", partName = "parameters")
    public GetCoordinatesResponse getCoordinates(
        @WebParam(name = "GetCoordinatesRequest", targetNamespace = "http://www.example.org/CityToCoordinatesService", partName = "parameters")
        GetCoordinatesRequest parameters);

}
